# Generated by Django 4.2 on 2023-07-30 19:29

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='confirmpassword',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='area_interesse',
            field=models.CharField(blank=True, choices=[('c', 'Contabilidade'), ('p', 'Plantio'), ('l', 'Colheita'), ('d', 'Distribuição'), ('i', 'Insumos')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=cpf_field.models.CPFField(error_messages={'invalid': 'Esse CPF não é válido'}, max_length=14),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(error_messages={'invalid': 'Essa data não é válida'}),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=2, error_messages={'invalid': 'Esse salário não é válido'}, max_digits=8),
        ),
    ]
